---

dbs_set_hostname: true
dbs_set_locale: true
dbs_set_timezone: true
dbs_set_ntp: true
dbs_hostname: "{{ inventory_hostname }}"
dbs_default_locale: "en_US.UTF-8"
dbs_locales:
  - "en_US.UTF-8"

dbs_ntp_hosts:
  - "0.fi.pool.ntp.org"
  - "1.fi.pool.ntp.org"
  - "2.fi.pool.ntp.org"
  - "3.fi.pool.ntp.org"
dbs_ntp_pkg: "ntp"

dbs_apt_default_host: "mirrordirector.raspbian.org"
dbs_apt_components: "main contrib non-free rpi"

docker_service_deploy_project_dir: /opt/docker_service
docker_service_deploy_pull: no

dbs_groups:
  - { name: 'docker' }

dbs_users:
  - { name: 'hass', groups: docker }
  - { name: 'postgres-hass', groups: docker }
  - { name: 'homebridge', groups: docker }
  - { name: 'mosca', groups: docker }
  - { name: 'duckdns' }

